### ISSUE TITLE
Failed to load from ./Model/QDL-CMFD-Model.hd5 / Error: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./Model/QDL-CMFD-Model.hd5

### ISSUE THREAD

**Issue by ShekharSengar** [MehradAria/QDL-CMFD#2]
please provide QDL-CMFD-Model.hd5 file.  During running of code following error occurred,  Failed to load from ./Model/QDL-CMFD-Model.hd5 / Error: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./Model/QDL-CMFD-Model.hd5

**Comment by arthur-qiu** [comment]
Do you solve it?

**Comment by MehradAria** [comment]
There is no plan to publish the trained model.
